apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy_httpd
  labels:
    name: chetan

spec: 
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
